openapi: 3.0.0
info:
  title: Alpha Laundry API
  version: 1.0.0
  description: API documentation for the Alpha Laundry Management System

servers:
  - url: http://localhost:3001/api
    description: Development server

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    Student:
      type: object
      properties:
        student_id:
          type: string
          format: string
        name:
          type: string
        remaining_quota:
          type: integer
          default: 30

    LaundryRequest:
      type: object
      properties:
        id:
          type: integer
        student_id:
          type: string
        num_clothes:
          type: integer
        status:
          type: string
          enum: [submitted, processing, completed]
        submission_date:
          type: string
          format: date-time

    Admin:
      type: object
      properties:
        username:
          type: string
        password_hash:
          type: string

paths:
  /login:
    post:
      summary: Login for students and admins
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Successful login
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string

  /student/dashboard:
    get:
      summary: Get student dashboard data
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Student dashboard data
          content:
            application/json:
              schema:
                type: object
                properties:
                  student:
                    $ref: '#/components/schemas/Student'
                  recent_requests:
                    type: array
                    items:
                      $ref: '#/components/schemas/LaundryRequest'

  /student/submit:
    post:
      summary: Submit new laundry request
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                num_clothes:
                  type: integer
      responses:
        '200':
          description: Request submitted successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LaundryRequest'

  /admin/dashboard:
    get:
      summary: Get admin dashboard data
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Admin dashboard data
          content:
            application/json:
              schema:
                type: object
                properties:
                  pending_requests:
                    type: array
                    items:
                      $ref: '#/components/schemas/LaundryRequest'
                  total_requests:
                    type: integer
                  completed_requests:
                    type: integer 